PORT = 3249 # Porta utilizada. Acima de 1024 e escolhida aleatoriamente
HOST = "localhost" # IP que iremos conectar o servidor e o cliente
PAYLOAD_SIZE = 1480 # Multiplos de 8
TESTE = True # Indica se estamos debugando
SERVIDOR = False # Indica se iremos rodar um Servidor ou um Cliente
SERVER_LISTEN = 32 # Numero de conexões maxima pelo servidor
TIMEOUT = 15 # Tempo de timeout em segundos
PACKET_SIZE = 512 # Tamanho de cada pacote
TEST_MESSAGE = "Testando o envio de strings"